spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma:2b

  datasource:
    url: jdbc:postgresql://localhost:5433/mcp_db
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true